### ISSUE TITLE
CFBundleVersion is empty 1.0.9

### ISSUE THREAD

**Issue by biloshkurskyi-ss** [ned1988/bitrise-step-git-tag-project-version-and-build-number#23]
I got this error 2 days ago. It works well before. I think it works with version 1.0.7 and after update to 1.0.9, this issue appeared.

```
+------------------------------------------------------------------------------+
| (2) git-tag-project-version-and-build-number@1                               |
+------------------------------------------------------------------------------+
| id: git-tag-project-version-and-build-number                                 |
| version: 1.0.9                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2020-05-27T15:11:37Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[15:11:37]  * [OK] Step dependency (git) installed, available. 
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise333126049/step_src/step.sh: line 9: ./read_bundle_version.sh: No such file or directory
CFBundleVersion is empty
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | git-tag-project-version-and-build-number@1 (exit code: 1)     | 2.85 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...1988/bitrise-step-git-tag-project-version-and-build-number |
| Source: ...com/ned1988/bitrise-step-git-tag-project-version-and-build-number |
+---+---------------------------------------------------------------+----------+
```

**Comment by denys-meloshyn** [comment]
@sergVn thanks for your report, will try to fix asap

**Comment by denys-meloshyn** [comment]
@sergVn new [PR](https://github.com/bitrise-io/bitrise-steplib/pull/2518) in review.
If you want to check how it works you can update your YML config:
```
    - git::https://github.com/ned1988/bitrise-step-git-tag-project-version-and-build-number.git@develop:
        inputs:
        - bitrise_tag_format: ...
        - bitrise_tag_xcodeproj_path: ...
        - bitrise_tag_info_plist_path: ...
```
